#!/bin/bash
#PBS -N lstm_gpu
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=4:mem=16gb:ngpus=1 
#PBS -j oe

module purge

module load tools/prod
module load Python/3.11.3-GCCcore-12.3.0
module load CUDA/11.7.0

source /rds/general/user/jc5322/home/venv/pycbcenv/bin/activate

cd "$PBS_O_WORKDIR"

echo "=== Testing it has a GPU ==="
python -c "import torch; print(torch.cuda.is_available())"

echo "=== Running lstm ==="
python lstm_rebuild.py